import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { BudgetBreakdown, BudgetFormData } from '../types';

export const generateBudgetPDF = (breakdown: BudgetBreakdown, formData: BudgetFormData, currencyCode: string = 'GHS') => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(0, 107, 63); // Ghana Green
    doc.text('GoGhana Trip Budget Estimate', 14, 20);

    // Trip Details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Duration: ${formData.duration} Days`, 14, 35);
    doc.text(`Travelers: ${formData.travelers || 1} (${formData.travelerType})`, 14, 42);
    doc.text(`Travel Style: ${formData.accommodationLevel}`, 14, 49);
    doc.text(`Regions: ${formData.regions?.join(', ') || 'Accra'}`, 14, 56);

    // Total Cost
    doc.setFontSize(16);
    doc.setTextColor(206, 17, 38); // Ghana Red
    doc.text(`Total Estimated Cost: ${currencyCode} ${breakdown.total.toLocaleString()}`, 14, 70);

    // Breakdown Table
    const tableData = [
        ['Accommodation', `${currencyCode} ${breakdown.accommodation.toLocaleString()}`],
        ['Food & Dining', `${currencyCode} ${breakdown.food.toLocaleString()}`],
        ['Transportation', `${currencyCode} ${breakdown.transport.toLocaleString()}`],
        ['Activities', `${currencyCode} ${breakdown.activities.toLocaleString()}`],
        ['Essentials', `${currencyCode} ${breakdown.essentials.toLocaleString()}`],
        ['Flights', `${currencyCode} ${breakdown.flights.toLocaleString()}`],
        ['Contingency (10%)', `${currencyCode} ${breakdown.contingency.toLocaleString()}`],
        ['TOTAL', `${currencyCode} ${breakdown.total.toLocaleString()}`]
    ];

    autoTable(doc, {
        startY: 80,
        head: [['Category', 'Amount']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [0, 107, 63] }, // Ghana Green
        footStyles: { fillColor: [206, 17, 38] }, // Ghana Red
    });

    // Regional Breakdown
    if (breakdown.regionalBreakdown && breakdown.regionalBreakdown.length > 0) {
        const regionalData = breakdown.regionalBreakdown.map(r => [
            r.region,
            `${currencyCode} ${r.dailyCost.toLocaleString()}/day`,
            `${currencyCode} ${r.totalCost.toLocaleString()}`
        ]);

        doc.text('Regional Breakdown', 14, (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15);

        autoTable(doc, {
            startY: (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20,
            head: [['Region', 'Daily Est.', 'Total Est.']],
            body: regionalData,
            theme: 'grid',
            headStyles: { fillColor: [252, 209, 22], textColor: [0, 0, 0] }, // Ghana Yellow (Gold)
        });
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text('Generated by GoGhana Budget Estimator', 14, doc.internal.pageSize.height - 10);
    }

    return doc;
};
